version: '3.4'

services:
  authServicedb:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2017-latest

  authservice.api:
    image: ${DOCKER_REGISTRY-}authserviceapi
    build:
      context: .
      dockerfile: Services/AuthService.Api/Dockerfile

  profileservice.api:
    image: ${DOCKER_REGISTRY-}profileserviceapi
    build:
      context: .
      dockerfile: Services/ProfileService.Api/Dockerfile


  apigateway.ocelot:
    image: ${DOCKER_REGISTRY-}apigatewayocelot
    build:
      context: .
      dockerfile: Services/ApiGateway.Ocelot/Dockerfile

