version: '3.4'

services:
  authServicedb:
    container_name: authServicedb
    environment:
        SA_PASSWORD: "Jerico05"
        ACCEPT_EULA: "Y"
        MSSQL_PID: Express
    restart: always
    ports:
      - "1434:1433" 

  authservice.api:
    container_name: authservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProfileServiceEndPoint=http://profileservice.api/api/v1/profile/createProfile"
    depends_on:
      - authServicedb
    ports:
      - "8000:80"
      - "443"
  profileservice.api:
    container_name: profileservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
      - "443"
  apigateway.ocelot:
    container_name: apigateway.ocelot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - profileservice.api
      - authservice.api
    ports:
      - "8010:80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
